apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-db-foo
  namespace: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo-db
        image: mongo
        volumeMounts:
          - name: mongo-persistent-storage-foo
            mountPath: /data/db
      volumes:
      - name: mongo-persistent-storage-foo
        persistentVolumeClaim: 
          claimName:  mongo-pvc-foo

       