apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: myapp
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo
        volumeMounts:
          - name: mongo-persistent-storage
            mountPath: "/mnt"
        volumes:
          -name: mongo-persistent-storage 
           persistentVolumeClaim:
             claimName: mongo-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi