apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-persistent-storage
  namespace: myapp
  labels : 
    release: stable
    type: local
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  hostPath:
    path: "/mnt/data"