apiVersion: v1
kind: persistentVolume
metadata:
  name: mongo-pvc
  namespace: myapp
spec:
  storageClassName: mylocalstorage
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  mountOptions:
    path: /mnt/somedirectory
    type: Directory


apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: myapp
spec:
  storageClassName: mylocalstorage
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 20Gi
  storageClassName: slow
  selector:
    matchLabels:
      release: "stable"