apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name}}-webapp
  labels:
    app: {{ .Values.app}}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ .Values.app}}
  template:
    metadata:
      labels:
        app: {{ .Values.app}}
    spec:
      containers:
      {{- include "webappImage" .| indent 8 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name}}-service
spec:
  selector:
    app.kubernetes.io/name: MyApp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376