apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- path:  patches/clusterRole.yaml
- path:  patches/Deployment.yaml
- path:  patches/svc.yaml
